<template>
  <div class="loadingio-spinner-pulse-9i18r49trvv mx-auto">
    <div class="ldio-b7hi67juwak">
      <div></div>
      <div></div>
      <div></div>
    </div>
  </div>
</template>

<style scoped>
@keyframes ldio-b7hi67juwak-1 {
  0% {
    top: 36px;
    height: 128px;
  }
  50% {
    top: 60px;
    height: 80px;
  }
  100% {
    top: 60px;
    height: 80px;
  }
}
@keyframes ldio-b7hi67juwak-2 {
  0% {
    top: 41.99999999999999px;
    height: 116.00000000000001px;
  }
  50% {
    top: 60px;
    height: 80px;
  }
  100% {
    top: 60px;
    height: 80px;
  }
}
@keyframes ldio-b7hi67juwak-3 {
  0% {
    top: 48px;
    height: 104px;
  }
  50% {
    top: 60px;
    height: 80px;
  }
  100% {
    top: 60px;
    height: 80px;
  }
}
.ldio-b7hi67juwak div {
  position: absolute;
  width: 30px;
}
.ldio-b7hi67juwak div:nth-child(1) {
  left: 35px;
  background: #44eea4;
  animation: ldio-b7hi67juwak-1 1s cubic-bezier(0, 0.5, 0.5, 1) infinite;
  animation-delay: -0.2s;
}
.ldio-b7hi67juwak div:nth-child(2) {
  left: 85px;
  background: #0affbe;
  animation: ldio-b7hi67juwak-2 1s cubic-bezier(0, 0.5, 0.5, 1) infinite;
  animation-delay: -0.1s;
}
.ldio-b7hi67juwak div:nth-child(3) {
  left: 135px;
  background: #9dfbdc;
  animation: ldio-b7hi67juwak-3 1s cubic-bezier(0, 0.5, 0.5, 1) infinite;
  animation-delay: undefineds;
}

.loadingio-spinner-pulse-9i18r49trvv {
  width: 200px;
  height: 200px;
  display: inline-block;
  overflow: hidden;
}
.ldio-b7hi67juwak {
  width: 100%;
  height: 100%;
  position: relative;
  transform: translateZ(0) scale(1);
  backface-visibility: hidden;
  transform-origin: 0 0; /* see note above */
}
.ldio-b7hi67juwak div {
  box-sizing: content-box;
}
/* generated by https://loading.io/ */
</style>
